<?php

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
?>
<div class="custom-footer">
    <div class="footer-top">
        <div class="footer-icon">
            <img src="<?= $block->getViewFileUrl('Magento_Theme::images/heart.png'); ?>" alt="heart icon" />
        </div>
        <div class="footer-subscribe">
            <div class="label-text">
                <h3>
                    <?= $escaper->escapeHtml(__('HEY KUMARI!')) ?>
                </h3>
                <p>
                    <?= $escaper->escapeHtml(__('Let us in on your inner circle for some fantastic offers.')) ?>
                </p>
            </div>
            <form action="#" method="post" data-mage-init='{"validation":{}}'>
                <div class="subscribe-group">
                    <input type="email" 
                            name="email"
                            placeholder="Email"
                            data-validate="{'validate-email':true,'required':true}"
                    >
                    <button type="submit" class="subscribe-button">
                        <?= $escaper->escapeHtml(__('SUBSCRIBE')) ?>
                    </button>
                </div>
            </form>
        </div>
    </div>

    <div class="footer-links">
        <div class="footer-columns">
            <div class="footer-column">
                <h4>
                    <?= $escaper->escapeHtml(__('KUMARI GUIDES')) ?>
                </h4>
                <ul>
                    <li>
                        <a href="#">
                            <?= $escaper->escapeHtml(__('Style Guide')) ?>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <?= $escaper->escapeHtml(__('Size Guide')) ?>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <?= $escaper->escapeHtml(__('Gemstone Guide')) ?>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <?= $escaper->escapeHtml(__('Diamond Guide')) ?>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <?= $escaper->escapeHtml(__('Metal Guide')) ?>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <?= $escaper->escapeHtml(__('Gift Guide')) ?>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <?= $escaper->escapeHtml(__('Care Guide')) ?>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="footer-column">
                <h4>
                    <?= $escaper->escapeHtml(__('LET US HELP')) ?>
                </h4>
                <ul>
                    <li>
                        <a href="#">
                            <?= $escaper->escapeHtml(__('Order Status')) ?>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <?= $escaper->escapeHtml(__('Shipping & Returns')) ?>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <?= $escaper->escapeHtml(__('Buyback & Exchange')) ?>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <?= $escaper->escapeHtml(__('Cancellation & Refund')) ?>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <?= $escaper->escapeHtml(__('FAQs')) ?>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <?= $escaper->escapeHtml(__('Contact Us')) ?>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="footer-column">
                <h4><?= $escaper->escapeHtml(__('ABOUT US')) ?></h4>
                <ul>
                    <li>
                        <a href="#">
                            <?= $escaper->escapeHtml(__('Our Story')) ?>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <?= $escaper->escapeHtml(__('Store Locator')) ?>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <?= $escaper->escapeHtml(__('In the Press')) ?>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <?= $escaper->escapeHtml(__('Customer Reviews')) ?>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <?= $escaper->escapeHtml(__('Blog')) ?>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="footer-column">
                <h4>
                    <?= $escaper->escapeHtml(__('LEGAL')) ?>
                </h4>
                <ul>
                    <li>
                        <a href="#">
                            <?= $escaper->escapeHtml(__('Terms & Conditions')) ?>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <?= $escaper->escapeHtml(__('Always Extra Scheme -T&Cs')) ?>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <?= $escaper->escapeHtml(__('Privacy Policy')) ?>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <?= $escaper->escapeHtml(__('Insurance Policy')) ?>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="footer-column payments">
                <h4>
                    <?= $escaper->escapeHtml(__('ACCEPTED PAYMENTS')) ?>
                </h4>
                <div class="payment-icons">
                    <img src="<?= $block->getViewFileUrl('Magento_Theme::images/amex.png'); ?>" alt="Amex" />
                    <img src="<?= $block->getViewFileUrl('Magento_Theme::images/visa.png'); ?>" alt="Visa" />
                    <img src="<?= $block->getViewFileUrl('Magento_Theme::images/paypal.png'); ?>" alt="PayPal" />
                </div>
            </div>
        </div>
    </div>

    <div class="footer-bottom">
        <p>
            <?= $escaper->escapeHtml(__('Copyright © 2025, D.P. Jewelline Private Limited.')) ?>
        </p>
        <div class="social-media-icon">
            <img src="<?= $block->getViewFileUrl('Magento_Theme::images/twitter.png'); ?>" alt="Twitter" />
            <img src="<?= $block->getViewFileUrl('Magento_Theme::images/pinterest.png'); ?>" alt="Pinterest" />
            <img src="<?= $block->getViewFileUrl('Magento_Theme::images/youtube.png'); ?>" alt="Youtube" />
            <img src="<?= $block->getViewFileUrl('Magento_Theme::images/facebook.png'); ?>" alt="Facebook" />
            <img src="<?= $block->getViewFileUrl('Magento_Theme::images/instagram.png'); ?>" alt="Instagram" />
            <img src="<?= $block->getViewFileUrl('Magento_Theme::images/linkedin.png'); ?>" alt="Linkdin" />
        </div>
    </div>
</div>
